[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get --assume-yes install wget unzip",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip",
    "unzip protoc-3.6.1-linux-x86_64.zip -d protoc-3.6.1",
    "mv protoc-3.6.1/bin/protoc /usr/bin/.",
]
